package projectoop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Personal
 */
public class MainMenu extends javax.swing.JFrame {
    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null;
    Statement St = null;
    /**
     * Creates new form RegistersCoba
     */
    public MainMenu() {
        initComponents();
    }
    
    String Username;
    double Balance;
    String PhoneNumber;
    int IdUser;
    public MainMenu(int id_user, String uName, double bal, String Phone){
        initComponents();
        IdUser = id_user;
        PhoneNumber = Phone;
        Username = uName;
        nameLabel_Menu.setText(""+uName);
        Balance = bal;
        balanceLabel_Menu.setText(""+bal);
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        headerPanel_Menu = new javax.swing.JPanel();
        nameLabel_Menu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        balanceLabel_Menu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        viewProfileButton_Menu = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        depoBalanceButton_Menu = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        wdBalanceButton_Menu = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        transferBalanceButton_Menu = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        utpButton_Menu = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        showTransactionButton_Menu = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        logoutButton_Menu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel_Menu.setBackground(new java.awt.Color(247, 247, 247));
        headerPanel_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel_Menu.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        nameLabel_Menu.setForeground(new java.awt.Color(0, 102, 153));
        nameLabel_Menu.setText("\"name\"");
        headerPanel_Menu.add(nameLabel_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 50));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Welcome,");
        headerPanel_Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 24));

        jPanel1.add(headerPanel_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 85));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Balance");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 34));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Rp.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 34));

        balanceLabel_Menu.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        balanceLabel_Menu.setForeground(new java.awt.Color(255, 255, 255));
        balanceLabel_Menu.setText("\"nominal\"");
        jPanel1.add(balanceLabel_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 350, 34));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/icon/Artboard 4 copy.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        jLabel5.setText("View Profile");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 50));

        viewProfileButton_Menu.setBackground(new java.awt.Color(252, 252, 252));
        viewProfileButton_Menu.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        viewProfileButton_Menu.setToolTipText("");
        viewProfileButton_Menu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        viewProfileButton_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewProfileButton_MenuMouseClicked(evt);
            }
        });
        viewProfileButton_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileButton_MenuActionPerformed(evt);
            }
        });
        jPanel1.add(viewProfileButton_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 180, 100));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/icon/Artboard 4 copy 2.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, 40));

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        jLabel11.setText("Deposit Balance");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, 50));

        depoBalanceButton_Menu.setBackground(new java.awt.Color(252, 252, 252));
        depoBalanceButton_Menu.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        depoBalanceButton_Menu.setToolTipText("");
        depoBalanceButton_Menu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        depoBalanceButton_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depoBalanceButton_MenuMouseClicked(evt);
            }
        });
        depoBalanceButton_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depoBalanceButton_MenuActionPerformed(evt);
            }
        });
        jPanel1.add(depoBalanceButton_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 180, 100));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/icon/Artboard 4 copy 3.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jLabel13.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        jLabel13.setText("Withdraw Balance");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, 50));

        wdBalanceButton_Menu.setBackground(new java.awt.Color(252, 252, 252));
        wdBalanceButton_Menu.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        wdBalanceButton_Menu.setToolTipText("");
        wdBalanceButton_Menu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        wdBalanceButton_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wdBalanceButton_MenuMouseClicked(evt);
            }
        });
        wdBalanceButton_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wdBalanceButton_MenuActionPerformed(evt);
            }
        });
        jPanel1.add(wdBalanceButton_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 180, 100));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/icon/Artboard 4 copy 4.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, 40));

        jLabel15.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        jLabel15.setText("Transfer Balance");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, 50));

        transferBalanceButton_Menu.setBackground(new java.awt.Color(252, 252, 252));
        transferBalanceButton_Menu.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        transferBalanceButton_Menu.setToolTipText("");
        transferBalanceButton_Menu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        transferBalanceButton_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferBalanceButton_MenuMouseClicked(evt);
            }
        });
        transferBalanceButton_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBalanceButton_MenuActionPerformed(evt);
            }
        });
        jPanel1.add(transferBalanceButton_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 180, 100));

        jLabel17.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        jLabel17.setText("Upgrade to Premium");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/icon/Artboard 4 copy 5.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, -1));

        utpButton_Menu.setBackground(new java.awt.Color(252, 252, 252));
        utpButton_Menu.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        utpButton_Menu.setToolTipText("");
        utpButton_Menu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        utpButton_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utpButton_MenuActionPerformed(evt);
            }
        });
        jPanel1.add(utpButton_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 180, 100));

        jLabel18.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        jLabel18.setText("Show Transaction");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, 20));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/icon/6.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, -1, -1));

        showTransactionButton_Menu.setBackground(new java.awt.Color(252, 252, 252));
        showTransactionButton_Menu.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        showTransactionButton_Menu.setToolTipText("");
        showTransactionButton_Menu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        showTransactionButton_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTransactionButton_MenuActionPerformed(evt);
            }
        });
        jPanel1.add(showTransactionButton_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 180, 100));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/icon/Artboard 4.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, -1, -1));

        logoutButton_Menu.setBackground(new java.awt.Color(248, 248, 248));
        logoutButton_Menu.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        logoutButton_Menu.setToolTipText("");
        logoutButton_Menu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logoutButton_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButton_MenuMouseClicked(evt);
            }
        });
        logoutButton_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButton_MenuActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 500, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/icon/Artboard 1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewProfileButton_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileButton_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewProfileButton_MenuActionPerformed

    private void depoBalanceButton_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depoBalanceButton_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depoBalanceButton_MenuActionPerformed

    private void wdBalanceButton_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wdBalanceButton_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wdBalanceButton_MenuActionPerformed

    private void transferBalanceButton_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBalanceButton_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferBalanceButton_MenuActionPerformed

    private void utpButton_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utpButton_MenuActionPerformed
        try{
                String QueryUtp = "select * from account where id_account="+IdUser+" and id_type=1";
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/primodb-test","root","");
                St = Con.createStatement();
                Rs = St.executeQuery(QueryUtp);
                if(Rs.next()){  
                    new UTPMenu(IdUser).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Account is Already Premium");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
    }//GEN-LAST:event_utpButton_MenuActionPerformed

    private void logoutButton_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButton_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButton_MenuActionPerformed

    private void viewProfileButton_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewProfileButton_MenuMouseClicked
        new ViewProfileMenu(IdUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewProfileButton_MenuMouseClicked

    private void logoutButton_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButton_MenuMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButton_MenuMouseClicked

    private void depoBalanceButton_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depoBalanceButton_MenuMouseClicked
        new AddMethodMenu(IdUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_depoBalanceButton_MenuMouseClicked

    private void wdBalanceButton_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wdBalanceButton_MenuMouseClicked
        new WDMethodMenu(IdUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_wdBalanceButton_MenuMouseClicked

    private void transferBalanceButton_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBalanceButton_MenuMouseClicked
            try{
                String QueryAcc = "select * from account where id_account="+IdUser+" and id_type=2";
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/primodb-test","root","");
                St = Con.createStatement();
                Rs = St.executeQuery(QueryAcc);
                if(Rs.next()){  
                    new TransferBalanceMenu(IdUser).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Account is Not Premium");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
    }//GEN-LAST:event_transferBalanceButton_MenuMouseClicked

    private void showTransactionButton_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTransactionButton_MenuActionPerformed
        new ShowTransaction(IdUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showTransactionButton_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel balanceLabel_Menu;
    public javax.swing.JButton depoBalanceButton_Menu;
    private javax.swing.JPanel headerPanel_Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton logoutButton_Menu;
    public javax.swing.JLabel nameLabel_Menu;
    public javax.swing.JButton showTransactionButton_Menu;
    public javax.swing.JButton transferBalanceButton_Menu;
    public javax.swing.JButton utpButton_Menu;
    public javax.swing.JButton viewProfileButton_Menu;
    public javax.swing.JButton wdBalanceButton_Menu;
    // End of variables declaration//GEN-END:variables
}
