package projectoop;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
/**
 *
 * @author Personal
 */
public class RegistersCoba extends javax.swing.JFrame {

    private Connection Connection;

    /**
     * Creates new form RegistersCoba
     */
    public RegistersCoba() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public RegistersCoba(Connection connection) {
        this.Connection = connection;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        backButton_Withdraw = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnLabel_Register = new javax.swing.JLabel();
        usernameLabel_Register = new javax.swing.JLabel();
        emailLabel_Register = new javax.swing.JLabel();
        passwordLabel_Register = new javax.swing.JLabel();
        backButton_Register = new javax.swing.JButton();
        cpLabel_Register = new javax.swing.JLabel();
        usernameTextField_Register = new javax.swing.JTextField();
        pnTextField_Register = new javax.swing.JTextField();
        emailTextField_Register = new javax.swing.JTextField();
        passwordTextField_Register = new javax.swing.JPasswordField();
        cpTextField_Register = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        registerButton_Register1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        backButton_Withdraw.setBackground(new java.awt.Color(0, 204, 255));
        backButton_Withdraw.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        backButton_Withdraw.setText("Back");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnLabel_Register.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        pnLabel_Register.setForeground(new java.awt.Color(255, 255, 255));
        pnLabel_Register.setText("Phone Number  ");
        jPanel1.add(pnLabel_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 450, -1, -1));

        usernameLabel_Register.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        usernameLabel_Register.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel_Register.setText("Username         ");
        jPanel1.add(usernameLabel_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 143, -1, -1));

        emailLabel_Register.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        emailLabel_Register.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel_Register.setText("Email                ");
        jPanel1.add(emailLabel_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 365, -1, -1));

        passwordLabel_Register.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        passwordLabel_Register.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel_Register.setText("Password          ");
        jPanel1.add(passwordLabel_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 217, -1, -1));

        backButton_Register.setBackground(new java.awt.Color(255, 255, 255));
        backButton_Register.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        backButton_Register.setText("Back");
        backButton_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButton_RegisterMouseClicked(evt);
            }
        });
        backButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton_RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(backButton_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 200, 45));

        cpLabel_Register.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        cpLabel_Register.setForeground(new java.awt.Color(255, 255, 255));
        cpLabel_Register.setText("Confirm Password");
        jPanel1.add(cpLabel_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 291, -1, -1));

        usernameTextField_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextField_RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(usernameTextField_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 180, 425, 30));

        pnTextField_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnTextField_RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(pnTextField_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 487, 425, 30));

        emailTextField_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextField_RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(emailTextField_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 402, 425, 30));
        jPanel1.add(passwordTextField_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 254, 425, 30));
        jPanel1.add(cpTextField_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 328, 425, 30));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PrimoWallet");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 69, -1, 35));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Register to");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 36, -1, 26));

        registerButton_Register1.setBackground(new java.awt.Color(255, 255, 255));
        registerButton_Register1.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        registerButton_Register1.setText("Register");
        registerButton_Register1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButton_Register1MouseClicked(evt);
            }
        });
        registerButton_Register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButton_Register1ActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton_Register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 200, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/icon/Artboard 1 copy 2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null;
    Statement St = null;
    int id_account;

    public void ClearTXT() {
        usernameTextField_Register.setText("");
        pnTextField_Register.setText("");
        passwordTextField_Register.setText("");
        emailTextField_Register.setText("");
        cpTextField_Register.setText("");
    }

    private void usernameTextField_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextField_RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextField_RegisterActionPerformed

    private void pnTextField_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnTextField_RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnTextField_RegisterActionPerformed

    private void emailTextField_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextField_RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextField_RegisterActionPerformed

    private void backButton_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButton_RegisterMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButton_RegisterMouseClicked

    private void registerButton_Register1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButton_Register1MouseClicked
                                  
    try {
        // Validasi input form
        if (usernameTextField_Register.getText().isEmpty() || pnTextField_Register.getText().isEmpty() ||
            passwordTextField_Register.getText().isEmpty() || cpTextField_Register.getText().isEmpty() ||
            emailTextField_Register.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information", "Message", JOptionPane.WARNING_MESSAGE);
            return; // Hentikan eksekusi jika ada data kosong
        }

        String username = usernameTextField_Register.getText();
        String email = emailTextField_Register.getText();
        String phoneNumber = pnTextField_Register.getText();
        String password = passwordTextField_Register.getText();
        String confirmPassword = cpTextField_Register.getText();

        // Validasi inputan sebelum ke database
        if (!Validation.isValidEmail(email)) {
            JOptionPane.showMessageDialog(this, "Invalid email format", "Message", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!Validation.isValidPhoneNumber(phoneNumber)) {
            JOptionPane.showMessageDialog(this, "Invalid phone number format", "Message", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!Validation.isValidPassword(password)) {
            JOptionPane.showMessageDialog(this, "Invalid password format", "Message", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match", "Message", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Koneksi database dan query untuk pengecekan username/email/phonenumber yang sama
        String checkUserSQL = "SELECT * FROM account a JOIN accountdetails ad ON a.id_account = ad.id_account WHERE a.username = ? OR ad.phonenumber = ? OR ad.email = ?";
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/primodb-test", "root", "");
        PreparedStatement checkStmt = con.prepareStatement(checkUserSQL);
        checkStmt.setString(1, username);
        checkStmt.setString(2, phoneNumber);
        checkStmt.setString(3, email);

        ResultSet rs = checkStmt.executeQuery();
        if (rs.next()) {
            // Jika user ditemukan dengan username, email, atau nomor telepon yang sama
            JOptionPane.showMessageDialog(this, "Username, phone number, or email already exists", "Message", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Koneksi database dan perintah SQL untuk memasukkan user baru
        String insertAccountSQL = "INSERT INTO account (id_account, id_type, username, password, balance) VALUES (?, ?, ?, ?, ?)";
        String insertDetailsSQL = "INSERT INTO accountdetails (id_account, email, phonenumber, NIK) VALUES (?, ?, ?, ?)";

        PreparedStatement addStmt = con.prepareStatement(insertAccountSQL, Statement.RETURN_GENERATED_KEYS);
        PreparedStatement detailsStmt = con.prepareStatement(insertDetailsSQL);

        addStmt.setNull(1, Types.INTEGER); // Asumsikan ID auto-increment
        addStmt.setInt(2, 1); // Role_id asumsikan 1 (default role)
        addStmt.setString(3, username);
        addStmt.setString(4, password);
        addStmt.setDouble(5, 0.0); // Balance awal = 0

        // Jalur sukses: akun ditambahkan
        int affectedRows = addStmt.executeUpdate(); 

        // Ambil id_account yang baru di-generate
        ResultSet generatedKeys = addStmt.getGeneratedKeys();
        if (generatedKeys.next()) {
            int id_account = generatedKeys.getInt(1); // ID baru dari tabel account

            // Menambahkan detail akun
            detailsStmt.setInt(1, id_account);
            detailsStmt.setString(2, email);
            detailsStmt.setString(3, phoneNumber);
            detailsStmt.setString(4, "0"); // Placeholder untuk NIK (atau field tambahan)
            detailsStmt.executeUpdate();
        }

        // Jalur sukses: pesan sukses dan reset form
        JOptionPane.showMessageDialog(this, "Registration Successful");
        ClearTXT();
        new Login().setVisible(true);
        this.dispose();

    } catch (SQLException e) {
        // Jalur error SQL atau masalah koneksi database
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // Jalur error umum
        JOptionPane.showMessageDialog(this, "Unexpected error: " + e.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_registerButton_Register1MouseClicked

    private void backButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton_RegisterActionPerformed

    }//GEN-LAST:event_backButton_RegisterActionPerformed

    private void registerButton_Register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButton_Register1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButton_Register1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistersCoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistersCoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistersCoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistersCoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistersCoba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backButton_Register;
    private javax.swing.JButton backButton_Withdraw;
    public javax.swing.JLabel cpLabel_Register;
    public javax.swing.JPasswordField cpTextField_Register;
    public javax.swing.JLabel emailLabel_Register;
    public javax.swing.JTextField emailTextField_Register;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel passwordLabel_Register;
    public javax.swing.JPasswordField passwordTextField_Register;
    public javax.swing.JLabel pnLabel_Register;
    public javax.swing.JTextField pnTextField_Register;
    public javax.swing.JButton registerButton_Register1;
    public javax.swing.JLabel usernameLabel_Register;
    public javax.swing.JTextField usernameTextField_Register;
    // End of variables declaration//GEN-END:variables
}
