package projectoop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
/**
 *
 * @author Personal
 */
public class ViewProfileMenu extends javax.swing.JFrame {

    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null;
    Statement St = null;
    ResultSet Rs2 = null;
    Statement St2 = null;

    /**
     * Creates new form RegistersCoba
     */
    public ViewProfileMenu() {
        initComponents();
    }

    String PhoneNumber;
    String uName;
    String Type;
    String eMail;
    int idUser;

    public ViewProfileMenu(int Id_User) {
        initComponents();
        idUser = Id_User;
        GetData();
        usernameLabel_ViewProfile.setText(uName);
        emailLabel_ViewProfile.setText(eMail);
        typeLabel_ViewProfile.setText(Type);
        pnLabel_ViewProfile.setText(PhoneNumber);
        setLocationRelativeTo(null);
    }

    private void GetData() {
        String Query = "select * from account where id_account=" + idUser;
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/primodb-test", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery(Query);

            // Move the cursor to the first row and check if there are results
            if (Rs.next()) {
                uName = Rs.getString(3);
                int tipe_akun = Rs.getInt(2);
                if (tipe_akun == 1) {
                    Type = "Reguler";
                } else {
                    Type = "Premium";
                }
                System.out.println(uName);
                // Now, query the account details based on the fetched accountId
                String Query2 = "select * from accountdetails where id_account=" + idUser;
                St2 = Con.createStatement();
                Rs2 = St2.executeQuery(Query2);
                if (Rs2.next()) {
                    eMail = Rs2.getString(3);
                    PhoneNumber = Rs2.getString(4);
                } else {
                    JOptionPane.showMessageDialog(this, "Account details not found.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Wrong Username or Password");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backButton_ViewProfile = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernameLabel_ViewProfile = new javax.swing.JLabel();
        emailLabel_ViewProfile = new javax.swing.JLabel();
        typeLabel_ViewProfile = new javax.swing.JLabel();
        pnLabel_ViewProfile = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(252, 252, 252));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Account Detail");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 24));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/icon/Artboard 4 copy.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 85));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username         ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 131, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Type");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 221, -1, -1));

        backButton_ViewProfile.setBackground(new java.awt.Color(0, 204, 255));
        backButton_ViewProfile.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        backButton_ViewProfile.setText("Back");
        backButton_ViewProfile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        backButton_ViewProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButton_ViewProfileMouseClicked(evt);
            }
        });
        backButton_ViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton_ViewProfileActionPerformed(evt);
            }
        });
        jPanel1.add(backButton_ViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 527, 185, 45));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 311, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 401, -1, -1));

        usernameLabel_ViewProfile.setFont(new java.awt.Font("Yu Gothic", 1, 28)); // NOI18N
        usernameLabel_ViewProfile.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel_ViewProfile.setText("\"Username\"");
        jPanel1.add(usernameLabel_ViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 168, 423, -1));

        emailLabel_ViewProfile.setFont(new java.awt.Font("Yu Gothic", 1, 28)); // NOI18N
        emailLabel_ViewProfile.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel_ViewProfile.setText("\"Email\"");
        jPanel1.add(emailLabel_ViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 348, 423, -1));

        typeLabel_ViewProfile.setFont(new java.awt.Font("Yu Gothic", 1, 28)); // NOI18N
        typeLabel_ViewProfile.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel_ViewProfile.setText("\"Type\"");
        jPanel1.add(typeLabel_ViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 258, 423, -1));

        pnLabel_ViewProfile.setFont(new java.awt.Font("Yu Gothic", 1, 28)); // NOI18N
        pnLabel_ViewProfile.setForeground(new java.awt.Color(255, 255, 255));
        pnLabel_ViewProfile.setText("\"PhoneNumber\"");
        jPanel1.add(pnLabel_ViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 438, 423, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/icon/Artboard 1 copy 2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButton_ViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton_ViewProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButton_ViewProfileActionPerformed

    private void backButton_ViewProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButton_ViewProfileMouseClicked
        String Query = "select * from account where id_account=" + idUser;

        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/primodb-test", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery(Query);

            // Move the cursor to the first row and check if there are results
            if (Rs.next()) {

                String Query2 = "select * from accountdetails where id_account=" + idUser;
                St2 = Con.createStatement();
                Rs2 = St2.executeQuery(Query2);

                if (Rs2.next()) {
                    // Now, launch the main menu with the relevant data
                    new MainMenu(Rs.getInt(1), Rs.getString(3), Rs.getDouble(5), Rs2.getString(4)).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Account details not found.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Wrong Username or Password");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_backButton_ViewProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProfileMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProfileMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProfileMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProfileMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProfileMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backButton_ViewProfile;
    public javax.swing.JLabel emailLabel_ViewProfile;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel pnLabel_ViewProfile;
    public javax.swing.JLabel typeLabel_ViewProfile;
    public javax.swing.JLabel usernameLabel_ViewProfile;
    // End of variables declaration//GEN-END:variables
}
